describe('Blogs ', function() {
  beforeEach(function() {
    cy.visit('http://localhost:3000')
  })

  it('front page can be opened', function() {
    cy.contains('log in to application')
  })

  it('user can be logged', function() {
    cy.get('#username')
      .type('janh2978')
    cy.get('#password')
      .type('03ago1995')
    cy.get('[data-cy=submit]')
      .click()
  })

  describe('Blogs state', function() {  
    beforeEach(function() {
      cy.request('POST', 'http://localhost:3003/api/testing/reset')
      const user = {      
        username: 'egroj33',
        name: 'Alejandro Huapaya',
        password: '03ago1995'      
      }
      cy.request('POST', 'http://localhost:3003/api/users', user)
      cy.visit('http://localhost:3000')
    })
  
    it('user can be logged', function() {
      cy.get('#username')
        .type('egroj33')
      cy.get('#password')
        .type('03ago1995')
      cy.get('[data-cy=submit]')
        .click()
    })
  
    it('new blog can be created', function() {
      cy.get('#username')
        .type('egroj33')
      cy.get('#password')
        .type('03ago1995')
      cy.get('[data-cy=submit]')
        .click()
      cy.get('[data-cy=newBlog]')
        .click()
      cy.get('#title')
        .type('New Blog Test')
      cy.get('#author')
        .type('Alejandro Huapaya')
      cy.get('#url')
        .type('https://www.testBlog.com')
      cy.get('[data-cy=create]')
        .click()
    })

    it('a new comment can be added in a new blog', function() {
      cy.get('#username')
        .type('egroj33')
      cy.get('#password')
        .type('03ago1995')
      cy.get('[data-cy=submit]')
        .click()
      cy.get('[data-cy=newBlog]')
        .click()
      cy.get('#title')
        .type('New Blog Test')
      cy.get('#author')
        .type('Alejandro Huapaya')
      cy.get('#url')
        .type('https://www.testBlog.com')
      cy.get('[data-cy=create]')
        .click()
      cy.get('#Blog-0')
        .click()
      cy.get('#comment')
        .type('Test comment')
      cy.get('[data-cy=addComment]')
        .click()
    })

    it('a new blog can be liked', function() {
      cy.get('#username')
        .type('egroj33')
      cy.get('#password')
        .type('03ago1995')
      cy.get('[data-cy=submit]')
        .click()
      cy.get('[data-cy=newBlog]')
        .click()
      cy.get('#title')
        .type('New Blog Test')
      cy.get('#author')
        .type('Alejandro Huapaya')
      cy.get('#url')
        .type('https://www.testBlog.com')
      cy.get('[data-cy=create]')
        .click()
      cy.get('#Blog-0')
        .click()
      cy.get('[data-cy=like]')
        .click()
    })

    it('new blog can be removed', function() {
      cy.get('#username')
        .type('egroj33')
      cy.get('#password')
        .type('03ago1995')
      cy.get('[data-cy=submit]')
        .click()
      cy.get('[data-cy=newBlog]')
        .click()
      cy.get('#title')
        .type('New Blog Test')
      cy.get('#author')
        .type('Alejandro Huapaya')
      cy.get('#url')
        .type('https://www.testBlog.com')
      cy.get('[data-cy=create]')
        .click()
      cy.get('#Blog-0')
        .click()
      cy.get('[data-cy=remove]')
        .click()
    })
  })  
})
